server:
  port: 8080

spring:
  application:
    name: shop
    
  # 데이터베이스 설정
  datasource:
    # 개발용 H2 DB (메모리)
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
    # 운영용 MariaDB (주석 해제하여 사용)
    # url: jdbc:mariadb://localhost:3306/online_shop
    # username: shop_user
    # password: shop_password
    # driver-class-name: org.mariadb.jdbc.Driver
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발시에만 사용, 운영시 validate로 변경
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # MariaDB 사용시 MariaDBDialect로 변경
        format_sql: true
        
  # H2 콘솔 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
# JWT 설정
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24시간

# 파일 업로드 경로
file:
  upload-dir: uploads/

# 로깅 설정
logging:
  level:
    com.example.shop: DEBUG
    org.springframework.security: DEBUG
