server:
  port: 8080

spring:
  application:
    name: shop
    
  # 데이터베이스 설정 - MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/shopdb
    username: root  # 또는 생성한 사용자명
    password: "1234"    # MariaDB 비밀번호 입력
    driver-class-name: org.mariadb.jdbc.Driver
    
    # 커넥션 풀 설정
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ShopHikariCP
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # create-drop에서 update로 변경 (데이터 보존)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect  # MariaDB 문법으로 변경
        format_sql: true
        use_sql_comments: true
        
  # H2 콘솔 비활성화 (MariaDB 사용하므로)
  h2:
    console:
      enabled: false
      
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
# JWT 설정
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24시간

# 파일 업로드 경로
file:
  upload-dir: uploads/

# 로깅 설정
logging:
  level:
    com.example.shop: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE